### ISSUE TITLE
Display relative path names in the rename summary

### ISSUE THREAD

**Issue by KasparEtter** [jhotmann/node-rename-cli#13]
When renaming with `rename --verbose '**/*.*' …`, you cannot see which files reside in which directory. It would be useful either to see the file path relative to the working directory or to group the renames by directory. If this is not desirable as a default, such a feature could also be opt-in with an option.

**Comment by jhotmann** [comment]
Code committed. Will be released with 6.2.0

Displays relative path if in the current directory or forward in the tree, will display full path otherwise.
