### ISSUE TITLE
Proceed after a single character without having to press enter

### ISSUE THREAD

**Issue by KasparEtter** [jhotmann/node-rename-cli#14]
This is really a detail but using this tool would be faster (and thus more pleasurable) if the prompts would continue after entering a single character without having to press enter. Both for:

```
Would you like to proceed? (y/n)
```

and

```
[…] already exists. What would you like to do?
1) Overwrite the file
2) Keep both files
3) Skip
Please input a number:
```

I'm not sure whether this is easily possible with the package that you are using. In Bash, I like to use the following:

```bash
read -p "Would you like to proceed? (y/n) " -n 1 -r
echo
if [ $REPLY = 'y' ]
then
    echo "Proceed."
else
    echo "Abort."
fi
```

**Comment by jhotmann** [comment]
This will be included in 7.0.0 Beta 2
