### ISSUE TITLE
[PENDING] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [jhotmann/node-rename-cli#6]
Dear Mr. Hotmann,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Node?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by jhotmann** [comment]
@sergeevabc I'm close to releasing version 5.0 and I just tested a compiled exe and it seems basic functionality works.  With the 5.0 release I will include an exe with the stipulation that it will be basically untested and things may be broken.

**Comment by jhotmann** [comment]
Version 5.0.0 release, Windows exe included on the release page https://github.com/jhotmann/node-rename-cli/releases/tag/5.0.0
