### ISSUE TITLE
German umlaute does not show correct

### ISSUE THREAD

**Issue by ReggaePanda** [jhotmann/node-rename-cli#8]
<img width="236" alt="bildschirmfoto 2018-08-22 um 11 10 07" src="https://user-images.githubusercontent.com/2183135/44454493-fe805e00-a5fb-11e8-8ffe-19d2eb1e21f3.png">
<img width="574" alt="bildschirmfoto 2018-08-22 um 11 09 56" src="https://user-images.githubusercontent.com/2183135/44454497-004a2180-a5fc-11e8-8618-60ca92aba3da.png">

the second file name with an `ä` does not show correctly in the preview

**Comment by jhotmann** [comment]
This is an interesting one. I'll have to do some digging as I didn't really take into account other languages when building this.

@ReggaePanda in MacOS is your language set to German or English (or something else)?

**Comment by ReggaePanda** [comment]
@jhotmann my language is set to German. and yes my file names has still German umlaute.

<img width="1219" alt="bildschirmfoto 2018-08-24 um 08 09 48" src="https://user-images.githubusercontent.com/2183135/44568004-26470180-a775-11e8-8183-abd03046c1db.png">
