### ISSUE TITLE
Navigation using arrow keys

### ISSUE THREAD

**Issue by HeavyJab** [jhotmann/node-rename-cli#9]
Is it possible to navigate using arrow keys or have I just missed it in the document?

**Comment by jhotmann** [comment]
@HeavyJab 
I've looked into this and the library I use for the terminal UI \([blessed](https://github.com/chjj/blessed)\) does not support cursor movement in the text box.

I may look into using other libraries in the future.

**Comment by jhotmann** [comment]
Switching to this library for terminal UI as it is in active development https://github.com/cronvel/terminal-kit

**Comment by jhotmann** [comment]
This is complete and will be included in the next 7.0.0 beta
